export const APPEND = 'APPEND';
export const CHANGE_ITEM = 'CHANGE_ITEM';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const NETWORKING_STARTED = 'NETWORKING_STARTED';
export const NETWORKING_FINISHED = 'NETWORKING_FINISHED';
export const NETWORK_ERROR = 'NETWORK_ERROR';

export const LOAD_SUCCEEDED = 'LOAD_SUCCEEDED';
export const SAVE_SUCCEEDED = 'SAVE_SUCCEEDED';

export const SET_FILTER = 'SET_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';