name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Loading source files from github
      uses: actions/checkout@v2
    - name: Installing Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing project dependencies
      run: npm install
    - name: Building project
      run: npm run build --if-present
    - name: Running tests
      run: npm test
    - name: Adding production git branch
      run: git branch production
    - name: Switching to production git branch
      run: git checkout production
    - name: Add build folder to commit
      run: git add -f ./build
    - name: Committing updates
      run: git commit -m "new production commit ${{github.sha}}" 
    - name: Pushing to production branch
      run: git push
      env:
        CI: true
