name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Loading source files from github
      uses: actions/checkout@v2
    - name: Installing Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Installing project dependencies
      run: npm install
    - name: Building project
      run: npm run build --if-present
    - name: Running tests
      run: npm test
      env:
        CI: true
    - name: Update build repo
      run: |
       echo $GITHUB_TOKEN
       echo $GITHUB_REPOSITORY
       echo ${GITHUB_REF}
       git remote add -f origin_build https://github.com/dimasorokin1987/react-dashboard-build.git
       #git subtree add --prefix=build origin_build master --squash
       git add -f ./build
       git commit -m'build update'
       git subtree push --prefix build origin_build master


